# -*- coding: utf-8 -*-
"""sentiment-analysis-model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rmtu_h8K0Jw8ILHl3BuGZGC_JYOAgLNB
"""

!pip install transformers datasets evaluate -q

import pandas as pd
import torch
from datasets import Dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments
import evaluate


csv_path = "/content/drive/MyDrive/ME/IMDB Dataset.csv"


df = pd.read_csv(csv_path)


dataset = Dataset.from_pandas(df)


def label_to_int(example):
    example['label'] = 1 if example['sentiment'] == 'positive' else 0
    return example

dataset = dataset.map(label_to_int)


dataset = dataset.train_test_split(test_size=0.2)


model_name = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)

# Tokenization with labels
def preprocess_function(examples):
    tokens = tokenizer(examples['review'], padding='max_length', truncation=True)
    tokens['labels'] = examples['label']
    return tokens

tokenized_datasets = dataset.map(preprocess_function, batched=True)


model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=2)


training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    report_to="none",
)


metric = evaluate.load("accuracy")


def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = torch.argmax(torch.tensor(logits), dim=-1)
    return metric.compute(predictions=predictions, references=labels)


trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets['train'],
    eval_dataset=tokenized_datasets['test'],
    compute_metrics=compute_metrics
)


trainer.train()

model.save_pretrained("/content/drive/MyDrive/my_models/distilbert_finetuned")
tokenizer.save_pretrained("/content/drive/MyDrive/my_models/distilbert_finetuned")

import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer
import evaluate

model_path = "/content/drive/MyDrive/my_models/distilbert_finetuned"

model = AutoModelForSequenceClassification.from_pretrained(model_path)
tokenizer = AutoTokenizer.from_pretrained(model_path)

metric = evaluate.load("accuracy")

def evaluate_model(eval_dataset):
    model.eval()
    all_logits = []
    all_labels = []

    for sample in eval_dataset:
        inputs = tokenizer(sample["review"], padding=True, truncation=True, return_tensors="pt")
        with torch.no_grad():
            outputs = model(**inputs)

        logits = outputs.logits
        all_logits.append(logits)


        label_tensor = torch.tensor([sample["label"]])
        all_labels.append(label_tensor)

    logits = torch.cat(all_logits, dim=0)
    predictions = torch.argmax(logits, dim=1)
    labels = torch.cat(all_labels, dim=0)

    acc = metric.compute(predictions=predictions, references=labels)
    return acc

def predict_sentiment(review_text):
    inputs = tokenizer(review_text, padding=True, truncation=True, max_length=512, return_tensors="pt")
    model.eval()
    with torch.no_grad():
        outputs = model(**inputs)
    logits = outputs.logits
    predicted_class_id = torch.argmax(logits, dim=1).item()
    return "Positive" if predicted_class_id == 1 else "Negative"

accuracy = evaluate_model(tokenized_datasets['test'])
print("Test Accuracy:", accuracy)

new_review = "The movie was fantastic and I loved it!"
print(predict_sentiment(new_review))